### ISSUE TITLE
Subscribed but app is not letting me add any other users

### ISSUE THREAD

**Issue by joemcmahon** [alienfamily/scanyourboxes#17]
Followed the flow, subscribed for the eye-watering $5.50 a month.

When I try to add another user, app cheerfully tells me I need to subscribe. Tapping Subscribe takes me to the screen that verifies that yes, I did subscribe.

Required a forced restart of the app to get the ability to add another user.

**Comment by alienfamily** [comment]
Hi,

Sorry for the late reply and thanks for the feedback.
Will try to reproduce the issue and make a fix ASAP.

**Comment by joemcmahon** [comment]
Thanks! I actually found that it was better to log in with the same ID on multiple devices; the boxes aren't pooled. which makes it harder to find things.

**Comment by alienfamily** [comment]
Issue is fixed. It was due to an incorrect verification of the subscription status after an authentication.

With the fix, when you will subscribe on a device (i.e.: your iPhone) and then authenticate on another device (i.e.: your iPad), your subscription will be checked and you will have your boxes on the iPad.

If the app request you to subscribe again on the second device (the iPad) then you will just need to restore your purchases on the device.

The new app version will be submitted to Apple shortly.

Thanks again for the feedback.
