### ISSUE TITLE
Can I revert to previous version of the app?

### ISSUE THREAD

**Issue by Sharonmichele4** [alienfamily/scanyourboxes#19]
I am unhappy about the changes to this new version. I have my boxes named with unique names and now they just show up as “objects” when I used to see the names of the boxes. And the pictures of the items in the boxes now display as a cropped, narrow rectangle- you can no longer see the entire picture. I have a lot of work invested in this app and am very frustrated that these changes make the app much less user friendly. Please advise me of what my options are. Thanks.
![08329DF7-D297-44C2-A517-4994AD52B849](https://user-images.githubusercontent.com/113266401/189503991-d7bb58be-e357-42d9-9334-bc9c265a7cb7.png)
![C7C0338F-51DD-4333-92A3-773A57E61AB4](https://user-images.githubusercontent.com/113266401/189503993-6de6bcd8-7cc1-4d4b-b733-94409720c029.png)

**Comment by alienfamily** [comment]
Hi,

Thanks for the feedback.

The boxes name should be displayed. It's an issue related dark mode. It will be fixed in the next release.

Concerning the picture ratio, i am afraid that it will stay this way because it's part of the new design of the app.
Sadly Apple doesn't provide the possibility to install a previous version of an app. You can only have one version of app available on the App Store.

Thanks again for the feedback.
